name: Build WolfAudio Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug and List Files
        run: |
          echo "Current directory files:"
          ls -R
          
      - name: Packaging
        run: |
          # هاد السطر كيقلب على المجلد اللي فيه plugin.xml باش يضمن أننا في المكان الصحيح
          if [ -d "data" ]; then
            echo "Data directory found."
            sudo chown -R 0:0 data/
            sudo chmod -R 755 data/
            sudo tar --owner=0 --group=0 -cvzf "WolfAudio.ngz" data/
          else
            echo "Error: 'data' directory not found at the root!"
            # هاد السطر كيعاوننا نعرفو فين كاين الملف بالضبط إذا كان وسط شي مجلد آخر
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfAudio-Package
          path: ./WolfAudio.ngz
