name: Build WolfAudio Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract Files
        run: |
          # هاد السطر كياخد الملف اللي عندك في image_f38fec.png وكيخرج منو المجلدات
          tar -xvf WolfAudio-Plugin.tar
          
      - name: Packaging
        run: |
          # دابا المجلد data خاصو يكون بان دابا بعد الفك
          if [ -d "data" ]; then
            sudo chown -R 0:0 data/
            sudo chmod -R 755 data/
            sudo tar --owner=0 --group=0 -cvzf "WolfAudio.ngz" data/
          else
            echo "Error: 'data' directory still not found after extraction!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WolfAudio-Package
          path: ./WolfAudio.ngz
